# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [41]:
import numpy as np, math, os, pathlib, types, textwrap, random
import pandas as pd
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
chessboard = np.zeros((10, 10), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [ ]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr = np.zeros((1000, 1000), dtype=np.float64)
print(arr.nbytes, "bytes")

8000000 bytes


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [ ]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a[[0, -1]] = a[[-1, 0]]  # Fancy indexing: swap first and last rows
print("After row swap:\n", a)

After row swap:
 [[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


In [ ]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
import numpy as np

# Step 1: Create a 3D array
a3d = np.arange(27).reshape(3, 3, 3)

# Step 2: Flatten using ravel (view if possible)
r = a3d.ravel()
r[0] = 999  # try modifying
print("\nAfter modifying ravel result:")
print("a3d[0,0,0] =", a3d[0,0,0])  # Should be 999 if ravel is a view

# Step 3: Flatten using flatten (always copy)
f = a3d.flatten()
f[1] = 888
print("\nAfter modifying flatten result:")
print("a3d[0,0,1] =", a3d[0,0,1])  # Should remain unchanged (1)

# Final check
print("\nFinal a3d array:\n", a3d)



After modifying ravel result:
a3d[0,0,0] = 999

After modifying flatten result:
a3d[0,0,1] = 1

Final a3d array:
 [[[999   1   2]
  [  3   4   5]
  [  6   7   8]]

 [[  9  10  11]
  [ 12  13  14]
  [ 15  16  17]]

 [[ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]]]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [ ]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
halves = np.array_split(xy, 2)
print('\nFirst half:', halves[0])
print('Second half:', halves[1])


First half: [1 3 5]
Second half: [2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


In [ ]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.

# Degrees array
degrees = np.array([0, 30, 45, 60, 90])

# Convert to radians
radians = np.radians(degrees)

# Compute sine values
sine_values = np.sin(radians)

# Display results
print("Degrees: ", degrees)
print("Radians: ", radians)
print("Sine values: ", sine_values)


Degrees:  [ 0 30 45 60 90]
Radians:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values:  [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


In [ ]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.

# Create row and column vectors
row = np.arange(1, 11).reshape(1, 10)  # shape (1, 10)
col = np.arange(1, 11).reshape(10, 1)  # shape (10, 1)

# Use broadcasting to multiply
multiplication_table = col * row

print("10×10 Multiplication Table:\n", multiplication_table)


10×10 Multiplication Table:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [ ]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
percentiles = np.percentile(data, [25, 50, 75])
print("25th, 50th, 75th percentiles:", percentiles)

25th, 50th, 75th percentiles: [30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [ ]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
die_rolls = rng.integers(1, 7, size=100)  # values in [1, 6]
count_6s = np.count_nonzero(die_rolls == 6)
proportion_6s = count_6s / 100

print("Number of 6s:", count_6s)
print("Proportion of 6s:", proportion_6s)

Number of 6s: 12
Proportion of 6s: 0.12


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np
from numpy.lib import recfunctions as rfn

# Original structured array
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                  dtype=[('name','U10'), ('age','i4'), ('weight','f4')])

print("Original:")
print(people['name'], people['age'].mean())

# Heights to add (must match shape)
heights = np.array([165.0, 175.5], dtype='f4')

# ✅ Add 'height' field
people_with_height = rfn.append_fields(people, 'height', heights, usemask=False)

print("\nAfter adding 'height' field:")
print(people_with_height)


Original:
['Alice' 'Bob'] 27.5

After adding 'height' field:
[('Alice', 25, 55. , 165. ) ('Bob', 30, 85.5, 175.5)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [ ]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


Eigenvalues of A: [ 2.11262499+0.j         -0.01021862+0.25306314j -0.01021862-0.25306314j]
Eigenvectors of A:
 [[ 0.70302163+0.j          0.33147588-0.23505815j  0.33147588+0.23505815j]
 [ 0.45089832+0.j         -0.72017792+0.j         -0.72017792-0.j        ]
 [ 0.54995573+0.j          0.45019904+0.33695104j  0.45019904-0.33695104j]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [ ]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.

# Step 1: Create the data array (same as stats section)
data = np.random.default_rng(0).integers(1, 100, size=(5, 4))
print("Original data:\n", data)

# Step 2: Save to CSV
np.savetxt("data.csv", data, delimiter=",", fmt="%d", header="Col1,Col2,Col3,Col4", comments='')

# Step 3: Load the CSV
loaded_data = np.loadtxt("data.csv", delimiter=",", skiprows=1)

# Step 4: Verify
print("\nLoaded data:\n", loaded_data)
print("Equal to original?", np.array_equal(data, loaded_data.astype(int)))


Original data:
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]

Loaded data:
 [[85. 64. 51. 27.]
 [31.  5.  8.  2.]
 [18. 81. 65. 91.]
 [50. 61. 97. 73.]
 [63. 54. 56. 93.]]
Equal to original? True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [ ]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
weekdays = dates.astype('datetime64[D]').astype('int64') % 7
mondays = np.sum(weekdays == 0)
print("Number of Mondays:", mondays)


Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


In [ ]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
# Sample 2D array with NaNs
arr = np.array([
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0]
])

# ✅ Compute column means ignoring NaNs
col_means = np.nanmean(arr, axis=0)

# ✅ Find indices where NaNs occur
inds = np.where(np.isnan(arr))

# ✅ Replace NaNs with corresponding column means
arr[inds] = np.take(col_means, inds[1])

print("Array after replacing NaNs with column means:")
print(arr)


Array after replacing NaNs with column means:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [39]:
from google.colab import files
uploaded = files.upload()

Saving fitness.txt to fitness (4).txt


In [40]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [46]:

# Convert to DataFrame
df = pd.DataFrame(fitness)

# Normalize column names to lowercase
df.columns = df.columns.str.strip().str.lower()

# Convert 'date' column to datetime with dayfirst format
df['date'] = pd.to_datetime(df['date'], dayfirst=True)

# Convert numeric columns to appropriate float types
df['step_count'] = pd.to_numeric(df['step_count'], errors='coerce')
df['mood'] = pd.to_numeric(df['mood'], errors='coerce')
df['calories_burned'] = pd.to_numeric(df['calories_burned'], errors='coerce')
df['hours_of_sleep'] = pd.to_numeric(df['hours_of_sleep'], errors='coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'], errors='coerce')

# 🟢 1. Monthly step count
monthly_steps = df.groupby(df['date'].dt.to_period('M'))['step_count'].sum()
print("Monthly Step Count:\n", monthly_steps)

# 🟢 2. Sleep vs Mood correlation
correlation = df['hours_of_sleep'].corr(df['mood'])
print("\nSleep vs Mood Correlation:", round(correlation, 3))

# 🟢 3. Weekly summary of calories burned
weekly_calories = df.groupby(df['date'].dt.to_period('W'))['calories_burned'].sum()
print("\nWeekly Calories Burned:\n", weekly_calories)



Monthly Step Count:
 date
2017-10     79051
2017-11    103071
2017-12     89565
2018-01     10163
Freq: M, Name: step_count, dtype: int64

Sleep vs Mood Correlation: 0.21

Weekly Calories Burned:
 date
2017-10-02/2017-10-08     378
2017-10-09/2017-10-15     765
2017-10-16/2017-10-22     657
2017-10-23/2017-10-29     521
2017-10-30/2017-11-05     665
2017-11-06/2017-11-12    1012
2017-11-13/2017-11-19     589
2017-11-20/2017-11-26     917
2017-11-27/2017-12-03     601
2017-12-04/2017-12-10     683
2017-12-11/2017-12-17     728
2017-12-18/2017-12-24     672
2017-12-25/2017-12-31     615
2018-01-01/2018-01-07     168
2018-01-08/2018-01-14       0
Freq: W-SUN, Name: calories_burned, dtype: int64


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*